import React from 'react'

function PrivacyPolicy() {
  return (
    <div>
      <h1>Privacy Policy</h1>
      <p>Ingredient Science, may be referred to in this Privacy Policy as "we," "us," "our" or other similar pronouns. Ingredient Science cares about your privacy. This privacy policy ("Policy" or "Privacy Policy") outlines, in general, the Personal Information and other information that is collected by Ingredient Science from consumers and how we use and protect it. This Policy governs your use of our consumer-directed websites, specifically those operated or maintained by Ingredient Science, (the "sites" or "websites") and Ingredient Science's collection of data through both online means and offline means, including printed promotional materials such as sweepstakes entry forms, coupons or other mail-in offers and telephone calls to Ingredient Science's consumer services department. The websites are intended for users who are located in the United States of America, and this Privacy Policy shall be interpreted under the laws of the United States.</p>
   
      <h2>You May be Contacted</h2>
      <p>Should you contact Ingredient Science in any form for the purpose of ordering a Ingredient Science product or receiving a Ingredient Science trial offer, Ingredient Science considers such an inquiry for a return contact. As such Ingredient Science may in fact contact you via telephone in order to follow up with you and help you complete you order. Accordingly, even if your contact information appears on any state or federal Do Not Contact lists, you acknowledge in such a case that you may receive a telephone call or other contact from Ingredient Science pursuant to your express business inquiry or transaction. You may stop us from calling you at any time by simply asking us to refrain from further calls to you. We maintain an internal no-call list and abide by all applicable laws relating to such.</p>
   
      <h2>Your California Privacy Rights</h2>
      <p>If you are a California resident and have shared Personal Information with us, a California law gives you the right to request and obtain from us, once per calendar year, information about how we have shared your Personal Information with third parties for their direct marketing purposes. You may send such requests to us via postal mail at: PO Box 1127, Downsview, ON M3J 0R2 or call us at 888-703-9850. If applicable, such information would include a list of the names and addresses of all third parties with whom Personal Information was shared during the prior calendar year for such third parties' marketing purposes, as well as a list of the categories of Personal Information shared during such prior calendar year. For additional information, see the Sharing Personal Information with Third Parties for Marketing Purposes section below.</p>

      <h2>Your Consent to This Privacy Policy</h2>
      <p>By providing Ingredient Science with Personal Information, by visiting Ingredient Science’s websites or by using various services and features offered by Ingredient Science (whether online or offline), you agree with the terms of our current Privacy Policy as posted here, as such terms may be amended from time to time</p>

      <h2>Collection of Personal Information</h2>
      <p>As used in this Privacy Policy, "Personal Information" means personally identifiable information such as your name, street address, telephone number, credit card and other payment information, screen name, e-mail address, wireless e-mail address, short message service or text message address, demographic information and other information that may identify you or allow online or offline contact with you. We may collect your Personal Information from you directly, or from third parties, and we may combine it with other information we collect about you from you or from third parties.</p>
      <p>We may also collect Personal Information from you about a third party. For example, you may be able to send an electronic "post card" to a friend, in which case we will need that person's name and e-mail address. Please note that we use such information only for the specified purpose (e.g., to mail the post card) and we will not contact such third party again unless the third party contacts us.</p>

      <h2>How We Use Your Information</h2>
      <p><strong>Our Use of Your Personal Information.</strong> When you provide your Personal Information to us, we will use it for the express purpose for which it was collected (e.g., to enter you in a sweepstakes or to send you a sample). It may also be used by the brand responsible for the website or promotion, as well as by our other brands, to contact you regarding other products and services which may be of interest to you (including those we may offer jointly with other companies). At any time, however, you may opt out of such contact (see Whom to Contact).</p>
      <p><strong>Sharing Personal Information with Third Parties for Marketing Purposes.</strong> We will not share your Personal Information with third parties for their marketing purposes without obtaining your prior consent. If you have granted us permission to share your Personal Information with such third party entities, such third parties' use of your Personal Information will be subject to their privacy policies. You should contact those entities directly regarding any communications you may receive from them, including if you later decide that you no longer want that third party to use your Personal Information.</p>
      <p><strong>Our Service Providers.</strong> At times we may retain third parties to help us operate our business. (e.g., to contact you for the purpose of helping you complete your order of an Ingredient Science product). These Service Providers may have access to your Personal Information for the purpose of performing these services for Ingredient Science but they are not authorized by us to use your Personal Information in any other way or for any other purpose.</p>
      <p><strong>Business Transfers.</strong> Ingredient Science does not sell Personal Information, except to an entity to which we divest all or a portion of our business (for example, in connection with our sale of a brand), or otherwise in connection with a merger, consolidation, change in control, reorganization or liquidation of all or a portion of our business.</p>
      <p><strong>Public Forums.</strong> When you contribute to a public area or feature of our website, such as a chat room, blog, message board or other open forum, the information that you submit to these areas or features may be made available to the general public. For this reason, we recommend that you do not use or submit any Personal Information, about yourself or others, on these areas of our website.</p>
      <p><strong>Legally Required Disclosures.</strong> We will release your Personal Information if required to do so by law, or by search warrant, subpoena or court order, and if we have a good faith belief that such disclosure is reasonably necessary to protect the rights, property or personal safety of Ingredient Science, its customers or the public.</p>

      <h2>Non-Personally-Identifiable Information We May Collect Online</h2>
      <p>We may use various technologies to collect non-personal information about your visits online so that we can tailor our sites and products to best suit your interests and needs.</p>
      <p><strong>Cookies.</strong> You may have heard of "cookies," which are small data files or pieces of information that are stored by your browser on your computer's hard drive. Ingredient Science may use cookies to collect information during and about your visits to our websites, such as the particular site areas you visit and the products or services you buy through our websites. Cookies may also be used to recognize that you have provided Personal Information to us and refrain from requesting the same information a second time (e.g., a username and/or password, or an e-mail address or other contact information).</p>
      <p>Most browsers are initially set to accept cookies, but can easily be set to refuse cookies. Note, however, that refusal of cookies may limit your ability to take full advantage of all the site features.</p>
      <p><strong>IP Address and Clickstream Data.</strong> Our servers collect information about your computer, such as your IP address, the type of Internet browser you are using and the type of computer operating system you are using. Such information may be used to personalize your web site experience, and to evaluate statistics about usage of our websites. Such information may be used anonymously and in the aggregate or may be linked to your Personal Information. Also, our server may record your activities as you navigate to, on and from our websites.</p>
      <p><strong>Clear GIFs.</strong> We may use pixel tags (also called clear gifs) or other similar tracking technologies in our websites and/or in our communications to collect information about your navigation on our websites, and to enable us to know whether you have visited a Web page or received a message. This information enables us to serve you and your interests better. Any or all of these activities with respect to website usage information (as described above in this section) may be performed on our behalf by our Service Providers.</p>

      <h2>Third Party Ad Servers</h2>
      <p>Advertisements on our site may be provided by third parties who manage them for us. Those third parties may employ cookies and clear gifs to recognize your computer each time they send you an online advertisement, and to measure advertising effectiveness. We do not control these companies' use of cookies and clear gifs. Some of these companies (like the ad networks) are members of the industry group, the Network Advertising Initiative, which offers a single location to opt out of their cookies.</p>
      
      <h2>Third Party Linked To Sites</h2>
      <p>When you are on our websites you may be able to visit, or link to, other sites which may be operated by unaffiliated third parties or by Ingredient Science, but which are not covered by this Privacy Policy. These sites may collect Personal Information about you, and you should check the privacy policies of the specific site you are visiting to understand your rights.</p>

      <h2>Privacy of Children Online</h2>
      <p>Ingredient Science is committed to protecting the online privacy of children and making the Internet safe for our users. Ingredient Science is not offered to children under the age of 18 years old, and will never knowingly collect information from minors. Minors should not place orders or provide personal information through this website.</p>

      <h2>Security of Information</h2>
      <p>We endeavor to keep your sensitive Personal Information secure from unauthorized access, modification and misuse. For example, we have a policy to restrict access to all Personal Information provided to the websites. Nevertheless, due to the inherent nature of the Internet as an open global communications vehicle, we cannot guarantee that information, during transmission through the Internet or while stored on our system or otherwise in our care, will be absolutely safe from intrusion by others, such as hackers.</p>
      <p>You may be able to create an account on our website with a username and password. In some cases, your username may be your e-mail address. If so, you are responsible for maintaining the strict confidentiality of your account password. We recommend that you choose a unique password for your website account and that you do not use any password that you also use for any other accounts which may contain your sensitive information, such as financial accounts or e-mail accounts. You agree to immediately notify Ingredient Science of any unauthorized use of your password or account or any other breach of security. We will not be responsible or liable for any loss or damage arising from your failure to comply with this provision.</p>
      <p>In the unlikely event that we believe that the security of your Personal Information in our possession or control may have been compromised, we may seek to notify you. If a notification is appropriate, we would endeavor to do so as promptly as possible under the circumstances, and, to the extent we have your e-mail address, we may notify you by e-mail. <strong>You consent to our use of e-mail as a means of such notification. If you prefer for us to use another method to notify you in this situation, please call 888-703-9850 with the alternative contact information you wish to be used.</strong></p>

      <h2>Changes to Our Policy</h2>
      <p>Ingredient Science reserves the right to change or remove this Privacy Policy at our discretion, so check back to this page from time to time to see such changes. For certain material changes to this Privacy Policy, we may notify you by additional means, such as by posting a notice on the front page of our website or sending you an e-mail.</p>

      <h2>Whom to Contact</h2>
      <p>Please write to us at PO Box 1127, Downsview, ON M3J 0R2 or call 888-703-9850, if you have any comments or questions about this Privacy Policy or to report any violations of the Privacy Policy. We will respond to you within seven days in most cases. For other requests, please choose among the following options:</p>
      <p>You may also opt out of our promotional e-mails by clicking on an opt-out link within the e-mail you receive, or opt out of one of our Mobile Message Service by texting the applicable "STOP" message to the short code associated with the particular program/service.</p>
      <p>Please understand that if you opt out of receiving promotional correspondence from us, we may still contact you in connection with your relationship, activities, transactions and communications with us. Also, if you have granted us permission to share your Personal Information with third party entities for their marketing purposes, you should contact those entities directly regarding any communications you may receive from them.</p>
      <p>If you are a parent (or guardian), and (1) you would like to <strong>correct or update, or have removed or deleted, any Personal Information that your child</strong> has sent us through a Ingredient Science site which is directed at children, (2) you would like to <strong>stop our further collection, use and/or disclosure of your child’s information</strong>, or (3) <strong>you don’t want your child to be contacted</strong> in the future by Ingredient Science, please click the appropriate button below.</p>
      <p>Ingredient Science will comply with the foregoing requests in accordance with applicable law.</p>
      <p>Last Updated: November 2013</p>
    </div>
  )
}

export default PrivacyPolicy